### ISSUE TITLE
Draft PWS Section 5.5.1 Transition Plan – Item # 3

### ISSUE THREAD

**Issue by vencoreinc** [18F/bpa-fedramp-dashboard#75] opened 2016-03-17 17:49 UTC
The government states that assistance may need to be provided to stand-up the application. Does the government expect this assistance to be provided within the sixty (60) day period of performance and can details of the expectation of this support be provided?  Vencore recommends including an optional Time and Materials (T&M) CLIN to support this work and provide funding as required.

**Comment by jposi** [comment] 2016-03-17 22:55
This appears to be a duplicate of issue #74 Please re-open and clarify if we are incorrect.

**Closed by jposi** 2016-03-17 22:55 UTC
Labels: Answered, question
